// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_k4gYXa-Fgs24NFSm6cb8y0lrmCtmv8',
    appId: '1:434971651875:web:f9f6be7a735a409765a696',
    messagingSenderId: '434971651875',
    projectId: 'alawtiluk-39587',
    authDomain: 'alawtiluk-39587.firebaseapp.com',
    storageBucket: 'alawtiluk-39587.firebasestorage.app',
    measurementId: 'G-GEHSXTP875',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgcTVVX-LBkPZ1hvVlhfVrlzzonn5t8Go',
    appId: '1:434971651875:android:5bc9d7503a971b3165a696',
    messagingSenderId: '434971651875',
    projectId: 'alawtiluk-39587',
    storageBucket: 'alawtiluk-39587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9o7DXN6nWVI9Tp4wlsnaUfdIp5WUuH-Y',
    appId: '1:434971651875:ios:b47e695986c07b2565a696',
    messagingSenderId: '434971651875',
    projectId: 'alawtiluk-39587',
    storageBucket: 'alawtiluk-39587.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9o7DXN6nWVI9Tp4wlsnaUfdIp5WUuH-Y',
    appId: '1:434971651875:ios:b47e695986c07b2565a696',
    messagingSenderId: '434971651875',
    projectId: 'alawtiluk-39587',
    storageBucket: 'alawtiluk-39587.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx_k4gYXa-Fgs24NFSm6cb8y0lrmCtmv8',
    appId: '1:434971651875:web:57e02eede1d7ea8a65a696',
    messagingSenderId: '434971651875',
    projectId: 'alawtiluk-39587',
    authDomain: 'alawtiluk-39587.firebaseapp.com',
    storageBucket: 'alawtiluk-39587.firebasestorage.app',
    measurementId: 'G-K4YST3H15S',
  );
}
